tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
# Unix
brew "git"
brew "openssl"
brew "zsh"
# Programming language prerequisites
brew "libyaml" # should come after OpenSSL
brew "coreutils"
cask "gpg-suite"
brew "libpq"
brew "readline"
brew "zlib"
# Package managers, CLIs
brew "asdf"
brew "awscli"
brew "gh" # github
brew "bash-completion"
brew "heroku/brew/heroku"
# Misc
brew "imagemagick" # for Rails to work with images
brew "postgresql", link: false
brew "redis"
brew "watch"
brew "z"
