#!/usr/bin/env bash

set -e

function brewUpdate {
  echo "Installing latest homebrew"
  which brew || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  brew update
  brew tap 'homebrew/bundle'
}

function brewInstall {
  echo "Installing brews"
  (cd brew && brew bundle install --cleanup)
}

function asdfInstall {
  # run after dotfiles linking so asdf-python will use default-python-packages
  echo "Installing asdf plugins"
  (cd asdf && (cat .tool-versions | awk '{system ("asdf plugin-add " $1)}'))
  (cd asdf && (cat .tool-versions | awk '{system("asdf install " $0)}'))
}

function linkCompletions {
  # TODO: make this part of installing docker?
  # https://docs.docker.com/docker-for-mac/#zsh
  etc=/Applications/Docker.app/Contents/Resources/etc
  ln -s $etc/docker.zsh-completion /usr/local/share/zsh/site-functions/_docker
  ln -s $etc/docker-compose.zsh-completion /usr/local/share/zsh/site-functions/_docker-compose
}

brewUpdate
brewInstall
./dotbot_install
asdfInstall
linkCompletions
